### ISSUE TITLE
Whole Package is outdated 

### ISSUE THREAD

**Issue by Zaeem20** [VineyS/danbot-status-py#6]
As DBH v2 released there is a whole changes in API done also:
previous API was:- https://danbot.host/nodeStatus
new one is this: -https://status.danbot.host/json/stats.json

you have to make some breaking changes in your package to revive it again

**Comment by VineyS** [comment]
Apparently, version 2 of danbot status i.e, https://status.danbot.host/json/stats.json is protected with cloudflare. In other words, we cannot do a get request via the normal method as Cloudflare blocks such requests preventing it from DDoS.

**Comment by Zaeem20** [comment]
You can use cfsscrape or cloudscraper for this 
If you want me to help u will u add me as a contributor???

**Comment by VineyS** [comment]
As mentioned in the README.md, this project is welcome to receive any sort of contributions.

**Comment by Zaeem20** [comment]
then add me please...

**Comment by VineyS** [comment]
Wdym add me please? You can be a contributor by creating Pull Requests

**Comment by VineyS** [comment]
Make sure that while creating the PR’s you should make sure the code runs with perfection and the default errors raised must be handled without having to crash the code.

**Comment by Zaeem20** [comment]
ok i will do a pull request with my code
